context("HTdescR")
library(HTdescR)

unit_test <- test_that("htdesc function", {
  #Workflow A (CltA returns reg.avg)
  CltA <- htdesc(smile = '*Cl', HT.type = 'taft', sigma.selection = 'A')
  expect_identical(CltA[[1]],1)
  expect_equal(CltA[[2]],3)
  expect_equal(CltA[[3]],'Cl*')
  expect_identical(CltA[[4]],2.36)
  #workflow B (ClmB returns hansch.pref, CNpB returns epi.value, BriB returns reg.avg)
  ClmB <- htdesc(smile = '*Cl', HT.type = 'meta', sigma.selection = 'B')
  expect_identical(ClmB[[1]],1)
  expect_equal(ClmB[[2]],3)
  expect_equal(ClmB[[3]],'Cl*')
  expect_identical(ClmB[[4]],0.37)
  CNpB <- htdesc(smile = "*C#N", HT.type = "para", sigma.selection = "B")
  expect_identical(CNpB[[1]],1)
  expect_equal(CNpB[[2]],7)
  expect_equal(CNpB[[3]],'*C#N')
  expect_identical(CNpB[[4]],0.70)
  BriB <- htdesc(smile = "*Br", HT.type = 'induction', sigma.selection = "B")
  expect_identical(BriB[[1]],1)
  expect_equal(BriB[[2]],4)
  expect_equal(BriB[[3]],'Br*')
  expect_identical(BriB[[4]],0.49)
  #workflow C (FtC returns epi, OHoC returns hansch.pref, returns avg.dist)
  FtC <- htdesc(smile = '*F', HT.type = 'taft', sigma.selection = 'C')
  expect_identical(FtC[[1]],1)
  expect_equal(FtC[[2]],2)
  expect_equal(FtC[[3]],'F*')
  expect_identical(FtC[[4]],2.72)
  OHoC <- htdesc(smile = '*O', HT.type = 'ortho', sigma.selection = 'C')
  expect_identical(OHoC[[1]],1)
  expect_equal(OHoC[[2]],204)
  expect_equal(OHoC[[3]],'O*')
  expect_identical(OHoC[[4]],-0.14)
  CCCOCoC <- htdesc(smile = '*COCCC', HT.type = 'ortho', sigma.selection = 'C')
  expect_identical(CCCOCoC[[1]],1)
  expect_equal(CCCOCoC[[2]],437)
  expect_equal(CCCOCoC[[3]],'CCCOC*')
  expect_identical(CCCOCoC[[4]],-0.34)
  #workflow D (CeD returns epi.value and returns avg.dist)
  CeD <- htdesc(smile = '*C', HT.type = 'es', sigma.selection = 'D')
  expect_identical(CeD[[1]],1)
  expect_equal(CeD[[2]],8)
  expect_equal(CeD[[3]],'C*')
  expect_identical(CeD[[4]],-1.12)
  CCFtD <- htdesc(smile = '*CCF', HT.type = 'taft', sigma.selection = 'D')
  expect_identical(CCFtD[[1]],1)
  expect_equal(CCFtD[[2]],348)
  expect_equal(CCFtD[[3]],'FCC*')
  expect_identical(CCFtD[[4]],-0.1)
})

unit_test
