context("HTdescR")
library(HTdescR)

unit_test <- test_that("htdesc function", {
  #Workflow A (CltA returns reg.avg)
  CltA <- htdesc(smile = '*Cl', HT.type = 'taft', sigma.selection = 'A')
  expect_identical(CltA[[1]],1)
  expect_equal(CltA[[2]],3)
  expect_equal(CltA[[3]],'Cl*')
  expect_identical(CltA[[4]],2.36)
  #workflow B (ClmB returns hansch.pref, CNpBreturns epi.value, BriB returns reg.avg)
  ClmB <- htdesc(smile = '*Cl', HT.type = 'meta', sigma.selection = 'B')
  expect_identical(ClmB[[1]],1)
  expect_equal(ClmB[[2]],3)
  expect_equal(ClmB[[3]],'Cl*')
  expect_identical(ClmB[[4]],0.37)
  CNpB <- htdesc(smile = "*C#N", HT.type = "para", sigma.selection = "B")
  expect_identical(CNpB[[1]],1)
  expect_equal(CNpB[[2]],7)
  expect_equal(CNpB[[3]],'*C#N')
  expect_identical(CNpB[[4]],0.70)
  BriB <- htdesc(smile = "*Br", HT.type = 'induction', sigma.selection = "B")
  expect_identical(BriB[[1]],1)
  expect_equal(BriB[[2]],4)
  expect_equal(BriB[[3]],'Br*')
  expect_identical(BriB[[4]],0.49)
})

unit_test
