#HTdescR libraries

library(BiocInstaller)
library(BiocStyle)
library(knitr)
library(rmarkdown)
library(testthat)
library(RUnit)
library(methods)
library(ChemmineR)
library(ChemmineOB)
library(BiocGenerics)
library(parallel)
library(fmcsR)
library(e1071)
library(hash)
library(pls)
library(randomForest)
library(stats)
library(tidyr)
library(utils)
library(dplyr)
library(FNN)


library(caTools)
library(stats)
library(tibble)
library(devtools)
library(caret)
